language: python
sudo: required
python:
- '3.6'
env:
  global:
  - TRAVIS_CI_OPERATOR=1
  - DOCKER_IMAGE=hasadna/migdar-data-pipelines
  - secure: SsiVQTBgNoXvzl6lcA7nZ+733nfPdn9IBcpUfluJTgXQvyaEnMiK2mDn/EYq4BjVUkdSHuV0ImTOghErb++SN+3VvJc8hEtIaAEAtci4130QDMqvzGtZ62BJM4kx6xL/XvPbVRKQGROZ5IsyL+FtWnCIOordhV4Ptrdrp5CbQaLbSgErEYRwd028g96svl2VQwc9gHKC4vj8/dkWNejeVZAmZy4mISZkzecPB7+SsNltkpep1W2qGeni4Jj9xEUaFaeurbP4qyPZF5dR/zf1NRAy+m/p4ykLGzImk0vUCM+iGBXF+WeF/Xngbvw6JuTFoXuoGdZXLzL3Mtc/E9qQh17/RRJZxt5qJIr90gIHUDD809Hai5wgXO1OwCXXRMV7OXROfU0d9jzVVkVpZZLQsldHItbDd0ZczYHeVwux37xzTxPR/l1H9i7qKdImF619H9whZrg+rJcVGk+L1/SoDP5PetSd/jf+dkB5kJtC5eH+IqEjDUnc7oi2m+f8M/GE9Yqs4dSgemlAAJZDJikpyCIrd12ZrN3dWwymUWP4RS6nndUIIJq9SK8mK2bQayNuM8/3MehyYOiUskNtUgMk1RSE+SnfZQ2BBAScPeXx32CkQiweHZSvkNizj5tIbDplpcmXJSYWbp5XXuQzPurE2PUFQtqr8reB2ed01SYdAlo=
  - secure: iKKD9QjsSvVGMhstEaXvnHNWy/skv5QlLA2RIbbqV9qR/XxnX+7Le9KXQUcUzN8AbfHZgqrw0p1ILCohPLbtKvxaeA35TUamnz7bNMMg5e1rxwzATIjb3uuG0zyhDydaXc2cniQ8T8SwylcwrXUD64TuFkUX8rjcHLGnzj+GsRhLFJnbxVS5twLPpbCoNWh6Zys0/dzHcB4ZrNhsyOsEZ/74w84q8fXTG3HF0npJBBqo4CfZzgzpkIoAcqNCejXSW5nfIwwxwNUrf6mdhpmWliCK4E/rBdHekuCf9Q8ASaqGJqxTAITUODjq4kdG85vJffAx1sU8tULsLwa2NkjLGyQVTNZ6Sf7apxsH5tZJ19Flm7LArzlrqmfCkPnivqgawYhiR4zuNLegDGU1bVjQdu8oF6zMM01ip2GectQBSeuUU3SBbTAII/quejVCXh2GoIVzKmI9C60vxcurpAh8iAFcY4imDxpRXu/jZSxma2/gzQhEnAkulej+hR+CgDSrJbFKCv2xXK4WtOEN/+u8EXN/dbPn/LRcfkIl9eHpM94iruzPatPr52JvF+vwO73dIQoyqVTzpNr7KnZZ67KmQDYM4yuQPRquhaDtnPuKL3XLf3C2jZCzBmCyS5z5yZSAGNpLUt9aGc5vt+sFv5qjJe91d8fuOQ0xWce5Bu5i3xo=
services:
- docker
install:
- curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh
  > $HOME/bin/travis_ci_operator.sh
- bash $HOME/bin/travis_ci_operator.sh init
- travis_ci_operator.sh docker-login
- bash .travis.sh install
script:
- bash .travis.sh script
deploy:
  provider: script
  script: bash .travis.sh deploy
  skip_cleanup: true
