name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build it
      env:
        DOCKER_IMAGE: "hasadna/migdar-data-pipelines"
        TRAVIS_CI_OPERATOR: "1"
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        mkdir $HOME/bin || true
        curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > $HOME/bin/travis_ci_operator.sh
        chmod +x $HOME/bin/travis_ci_operator.sh
        echo init
        $HOME/bin/travis_ci_operator.sh init
        echo docker-login
        $HOME/bin/travis_ci_operator.sh docker-login
        echo install
        ./.travis.sh install
        echo script
        ./.travis.sh script
        echo deploy
        ./.travis.sh deploy
