name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - env:
        DOCKER_IMAGE_NAME: "hasadna/migdar-data-pipelines"
        TRAVIS_CI_OPERATOR: "1"
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        mkdir bin
        curl -L https://raw.githubusercontent.com/OriHoch/travis-ci-operator/master/travis_ci_operator.sh > ./bin/travis_ci_operator.sh
        chmod +x ./bin/travis_ci_operator.sh
        echo init
        ./bin/travis_ci_operator.sh init
        echo docker-login
        ./bin/travis_ci_operator.sh docker-login
        echo install
        .travis.sh install
        echo script
        .travis.sh script
        echo deploy
        .travis.sh deploy
